### ISSUE TITLE
Reentrant function vulnerable to attacks in TokenBank.sol

### ISSUE THREAD

**Issue by mojtaba-eshghie** [MrToph/capture-the-ether#2]
Hi, 

I believe the following file in the function `withdraw` is vulnerable to being called multiple times and drained. 
https://github.com/MrToph/capture-the-ether/blob/master/contracts/miscellaneous/TokenBank.sol

The simplest solution is to use the checks-effects-interactions pattern, i.e., exchanging the order of lines [106](https://github.com/MrToph/capture-the-ether/blob/master/contracts/miscellaneous/TokenBank.sol#L106) and [107](https://github.com/MrToph/capture-the-ether/blob/master/contracts/miscellaneous/TokenBank.sol#L107).

**Comment by MrToph** [comment]
This is a CTF repo, the bugs are on purpose to teach people about security.
